/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ChatgptRouteImport } from './routes/chatgpt'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicMcpHealthRouteImport } from './routes/api/public/mcp-health'
import { Route as PSlugIndexRouteImport } from './routes/p.$slug.index'
import { Route as PSlugSplatRouteImport } from './routes/p.$slug.$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicReportsRunRouteImport } from './routes/api/public/reports/run'
import { Route as ApiPublicTrackClickRouteImport } from './routes/api/public/track/click'
import { Route as ApiPublicV1AnalyticsRouteImport } from './routes/api/public/v1/analytics'
import { Route as ApiPublicV1PresenceRouteImport } from './routes/api/public/v1/presence'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatgptRoute = ChatgptRouteImport.update({
  id: '/chatgpt',
  path: '/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMcpHealthRoute = ApiPublicMcpHealthRouteImport.update({
  id: '/api/public/mcp-health',
  path: '/api/public/mcp-health',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugIndexRoute = PSlugIndexRouteImport.update({
  id: '/p/$slug/',
  path: '/p/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugSplatRoute = PSlugSplatRouteImport.update({
  id: '/p/$slug/$',
  path: '/p/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReportsRunRoute = ApiPublicReportsRunRouteImport.update({
  id: '/api/public/reports/run',
  path: '/api/public/reports/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackClickRoute = ApiPublicTrackClickRouteImport.update({
  id: '/api/public/track/click',
  path: '/api/public/track/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AnalyticsRoute = ApiPublicV1AnalyticsRouteImport.update({
  id: '/api/public/v1/analytics',
  path: '/api/public/v1/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PresenceRoute = ApiPublicV1PresenceRouteImport.update({
  id: '/api/public/v1/presence',
  path: '/api/public/v1/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/chatgpt': typeof ChatgptRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/publish': typeof PublishRoute
  '/refunds': typeof RefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/mcp-health': typeof ApiPublicMcpHealthRoute
  '/p/$slug/$': typeof PSlugSplatRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/reports/run': typeof ApiPublicReportsRunRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/v1/analytics': typeof ApiPublicV1AnalyticsRoute
  '/api/public/v1/presence': typeof ApiPublicV1PresenceRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/chatgpt': typeof ChatgptRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/publish': typeof PublishRoute
  '/refunds': typeof RefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/mcp-health': typeof ApiPublicMcpHealthRoute
  '/p/$slug/$': typeof PSlugSplatRoute
  '/p/$slug': typeof PSlugIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/reports/run': typeof ApiPublicReportsRunRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/v1/analytics': typeof ApiPublicV1AnalyticsRoute
  '/api/public/v1/presence': typeof ApiPublicV1PresenceRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/chatgpt': typeof ChatgptRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/publish': typeof PublishRoute
  '/refunds': typeof RefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/mcp-health': typeof ApiPublicMcpHealthRoute
  '/p/$slug/$': typeof PSlugSplatRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/reports/run': typeof ApiPublicReportsRunRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/v1/analytics': typeof ApiPublicV1AnalyticsRoute
  '/api/public/v1/presence': typeof ApiPublicV1PresenceRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analytics'
    | '/chatgpt'
    | '/knowledge'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manage'
    | '/mcp'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/publish'
    | '/refunds'
    | '/sitemap.xml'
    | '/support'
    | '/team'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/mcp-health'
    | '/p/$slug/$'
    | '/p/$slug/'
    | '/api/public/payments/webhook'
    | '/api/public/reports/run'
    | '/api/public/track/click'
    | '/api/public/v1/analytics'
    | '/api/public/v1/presence'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analytics'
    | '/chatgpt'
    | '/knowledge'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manage'
    | '/mcp'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/publish'
    | '/refunds'
    | '/sitemap.xml'
    | '/support'
    | '/team'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/mcp-health'
    | '/p/$slug/$'
    | '/p/$slug'
    | '/api/public/payments/webhook'
    | '/api/public/reports/run'
    | '/api/public/track/click'
    | '/api/public/v1/analytics'
    | '/api/public/v1/presence'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/analytics'
    | '/chatgpt'
    | '/knowledge'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manage'
    | '/mcp'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/publish'
    | '/refunds'
    | '/sitemap.xml'
    | '/support'
    | '/team'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/mcp-health'
    | '/p/$slug/$'
    | '/p/$slug/'
    | '/api/public/payments/webhook'
    | '/api/public/reports/run'
    | '/api/public/track/click'
    | '/api/public/v1/analytics'
    | '/api/public/v1/presence'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChatgptRoute: typeof ChatgptRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ManageRoute: typeof ManageRoute
  McpRoute: typeof McpRoute
  PreviewRoute: typeof PreviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PublishRoute: typeof PublishRoute
  RefundsRoute: typeof RefundsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicMcpHealthRoute: typeof ApiPublicMcpHealthRoute
  PSlugSplatRoute: typeof PSlugSplatRoute
  PSlugIndexRoute: typeof PSlugIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicReportsRunRoute: typeof ApiPublicReportsRunRoute
  ApiPublicTrackClickRoute: typeof ApiPublicTrackClickRoute
  ApiPublicV1AnalyticsRoute: typeof ApiPublicV1AnalyticsRoute
  ApiPublicV1PresenceRoute: typeof ApiPublicV1PresenceRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt': {
      id: '/chatgpt'
      path: '/chatgpt'
      fullPath: '/chatgpt'
      preLoaderRoute: typeof ChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp-health': {
      id: '/api/public/mcp-health'
      path: '/api/public/mcp-health'
      fullPath: '/api/public/mcp-health'
      preLoaderRoute: typeof ApiPublicMcpHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/': {
      id: '/p/$slug/'
      path: '/p/$slug'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof PSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/$': {
      id: '/p/$slug/$'
      path: '/p/$slug/$'
      fullPath: '/p/$slug/$'
      preLoaderRoute: typeof PSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reports/run': {
      id: '/api/public/reports/run'
      path: '/api/public/reports/run'
      fullPath: '/api/public/reports/run'
      preLoaderRoute: typeof ApiPublicReportsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click': {
      id: '/api/public/track/click'
      path: '/api/public/track/click'
      fullPath: '/api/public/track/click'
      preLoaderRoute: typeof ApiPublicTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/analytics': {
      id: '/api/public/v1/analytics'
      path: '/api/public/v1/analytics'
      fullPath: '/api/public/v1/analytics'
      preLoaderRoute: typeof ApiPublicV1AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/presence': {
      id: '/api/public/v1/presence'
      path: '/api/public/v1/presence'
      fullPath: '/api/public/v1/presence'
      preLoaderRoute: typeof ApiPublicV1PresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChatgptRoute: ChatgptRoute,
  KnowledgeRoute: KnowledgeRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ManageRoute: ManageRoute,
  McpRoute: McpRoute,
  PreviewRoute: PreviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PublishRoute: PublishRoute,
  RefundsRoute: RefundsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicMcpHealthRoute: ApiPublicMcpHealthRoute,
  PSlugSplatRoute: PSlugSplatRoute,
  PSlugIndexRoute: PSlugIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicReportsRunRoute: ApiPublicReportsRunRoute,
  ApiPublicTrackClickRoute: ApiPublicTrackClickRoute,
  ApiPublicV1AnalyticsRoute: ApiPublicV1AnalyticsRoute,
  ApiPublicV1PresenceRoute: ApiPublicV1PresenceRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
